name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
          npm list

      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed"
          echo "Checking build output:"
          ls -la
          if [ -d "dist" ]; then
            echo "dist directory exists"
            ls -la dist
          else
            echo "Error: dist directory not found"
            exit 1
          fi

      - name: Create .nojekyll file
        run: |
          touch dist/.nojekyll
          echo "Created .nojekyll file"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true

      - name: Print deployment status
        run: |
          echo "Deployment completed"
          echo "Please check your site at https://annachen1228.github.io/blog/"
